// | Field Name      | Type               | Constraints/Description
// |-----------------|--------------------|----------------------------------------
// | ObjectId        | ObjectId           | Auto-generated by MongoDB
// | name            | String             | Required, trimmed
// | description     | String             | Required
// | price           | Number             | Required
// | discountPrice   | Number             | Optional
// | countInStock    | Number             | Required, default: 0
// | sku             | String             | Required, unique
// | category        | String             | Required
// | brand           | String             | Optional
// | sizes           | [String]           | Required, example: ['S', 'M', 'L']
// | colors          | [String]           | Required, example: ['Red', 'Blue']
// | collections     | String             | Required, example: 'Summer collection'
// | material        | String             | Optional
// | gender          | String             | Enum: ['Men', 'Women', 'Unisex']
// | images          | Array of Objects   | Required, each object contains:
// |                 |                    |   - url: String (required),
// |                 |                    |   - altText: String (optional)
// | isFeatured      | Boolean            | Default: false
// | isPublished     | Boolean            | Default: false
// | rating          | Number             | Default: 0
// | numReviews      | Number             | Default: 0
// | tags            | [String]           | Optional
// | user            | ObjectId           | Reference to User, required
// | metaTitle       | String             | Optional
// | metaDescription | String             | Optional
// | metakeywords    | String             | Optional
// | dimensions      | Object             | Optional, contains:
// |                 |                    |   - length: Number,
// |                 |                    |   - width: Number,
// |                 |                    |   - height: Number
// | weight          | Number             | Optional
// | createdAt       | Date               | Auto-generated by timestamps
// | updatedAt       | Date               | Auto-updated by timestamps
